plugin: aws_ec2

regions:
  - eu-central-1

filters:
  tag:AsgName:
    - dev-frontend-2026-08-asg
  instance-state-name: running

hostnames:
  - instance-id

compose:
  ansible_host: instance_id
  ansible_connection: "'community.aws.aws_ssm'"
  ansible_aws_ssm_region: "'eu-central-1'"
